language: java
jdk:
  - oraclejdk8
services:
  - mysql
dist: trusty
sudo: required
env:
  - MYSQL_HOST=localhost MYSQL_PORT=3306 MYSQL_DATABASE=17high MYSQL_USER=17high MYSQL_PASSWORD=17high
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS 17high;'
  - mysql -e "CREATE USER '17high'@'localhost' IDENTIFIED BY '17high';"
  - mysql -e "GRANT ALL ON 17high.* TO '17high'@'localhost';"
  - chmod +x deploy/*.sh
after_success:
  - docker login registry.cn-hangzhou.aliyuncs.com -u $ALI_DOCKER_USER -p $ALI_DOCKER_PASSWORD
  - deploy/docker_push.sh
  - docker logout
branches:
  only:
  - /.*/