version: '2'
services:
  database:
    image: "daocloud.io/library/mysql:5.7"
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=5ecret
     - MYSQL_USER=17high
     - MYSQL_PASSWORD=17high
     - MYSQL_DATABASE=17high
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
  17high:
      image: "registry.cn-hangzhou.aliyuncs.com/wjyao/17high_web"
      ports:
       - "8081:8080"
      environment:
       - MYSQL_HOST=database
       - MYSQL_DATABASE=17high
       - MYSQL_USER=17high
       - MYSQL_PASSWORD=17high
      links:
       - database