version: '2'
services:
  17high-Jenkins:
    image: "registry.cn-hangzhou.aliyuncs.com/lane0201/jenkins"
    ports:
      - "18080:8080"
    volumes:
      - ~/17high/jenkins/jenkins_home:/var/jenkins/jenkins_home
